public class TemplateSigningJSON {

    public class Signers {
        public String firstname;
        public String lastname;
        public String email;
        public Integer order;
    }
    
    public String zGroup;
    public String name;
    public String templatepdf;
    public List<Signers> signers;
    public String do_email;
    public Map<String, String> pdftext;
    public String convert_sender_to_signer;
    public String tag;
            
    
}